### ISSUE TITLE
Can I use this custom device on PXI Linux RTOS?

### ISSUE THREAD

**Issue by ghost** [NIVeriStandAdd-Ons/Chassis-TimeSync-Custom-Device#3]
I want to use this custom device for Time&Signal synchronization on VeriStand.

[https://www.ni.com/en-us/innovations/white-papers/13/using-synchronization-to-build-integration-test-systems-with-ver.html#10EtherCATDAQandorFPGASinglePointSingleChassis](url)

However, my system is PXI based **NI Linux RT OS** and **VeriStand 2019.**

**Is there any compatibility issue?**

**Comment by rtzoeller** [comment]
Hi @Kreative24hk,

this custom device does not support NI Linux RT, however the [**NI Synchronization custom device**](https://github.com/ni/niveristand-synchronization-custom-device/releases) does. The two should be functionally equivalent although the latter has slightly different status channels, as the status channels in this custom device are PharLap specific.

**Comment by rtzoeller** [comment]
I will follow up on getting the documentation you referenced to point to the new custom device.

**Comment by ghost** [comment]
Thanks @rtzoeller .

So, It means that I can use NI Synchronization custom device on behalf of Chassis Timesync Custom Device. Am I right understanding?

**Comment by rtzoeller** [comment]
Correct.
